### ISSUE TITLE
No error output makes it to console

### ISSUE THREAD

**Issue by vtomilin** [jednano/grunt-typescript#1]
typescript task, when fails to compile a typescript file, does not output error to the console. Instead, only `Warning: Uncaught, unspecified "error" event. Use --force to continue.` appears.

I run Windows XP, node 0.10.25, grunt-cli v0.1.13, grunt v0.4.2, grunt-typescript-compile v0.1.1.

![grunt-typescript](https://f.cloud.github.com/assets/1181134/2233224/5441fa5e-9b27-11e3-8336-a210d1e7e792.png)

**Comment by jednano** [comment]
What happens when you run `grunt --debug`?

**Comment by vtomilin** [comment]
@jedmao Then I get this:

![grunt-typescript](https://f.cloud.github.com/assets/1181134/2235296/7b816de2-9b46-11e3-9d68-3184137de70c.png)

**Comment by jednano** [comment]
I think this problem is in the ts-compiler. I can look into it this weekend.

**Comment by jednano** [comment]
Fixed in [ts-compiler](https://github.com/jedmao/ts-compiler), dependencies update. Do an `npm install --save-dev grunt-typescript-compile` or `--save` if that suits you.

**Comment by vtomilin** [comment]
@jedmao works great, thanks
